### ISSUE TITLE
auth with empty password

### ISSUE THREAD

**Issue by WebFreak001** [symmetryinvestments/ldapauth#1]
On the documentation page of flask-simpleldap I read:

> Many LDAP servers will grant anonymous access if password is the empty string, causing this method to return True no matter what username is given. If you want to use this method to validate a username and password, rather than actually connecting to the LDAP server as a particular user, make sure password is not empty.

what would happen in these cases in this library with the `login` method?

**Comment by burner** [comment]
I don't know.

ldapauth is basically a stripped down ldapwhoami.

If it is depended on the ldap server, as per your quote, this is also depended on ldap server.

I assume you asking because you have a specific need.

There is a usage example here https://github.com/symmetryinvestments/ldapauth/blob/master/source/ldap.d#L181

I guess compiling that and calling your server will likely get you your answer.

If this doesn't answer you question please reopen this issue.

**Comment by WebFreak001** [comment]
I was actually just asking because users could enter empty passwords and it is not handled by this library. So I would appreciate if the readme could include either that you need to check for empty passwords because of that quirk or if the return value of the login has some specific code for readonly access. (I haven't tried it out yet)

**Comment by burner** [comment]
I would counter that sometimes an empty password is the correct password. Not a good one, but a correct one.
